### ISSUE TITLE
Mixcr issues

### ISSUE THREAD

**Issue by kangxiongbin** [whhudson/spatialTCR#1]
Hi,
When I download your data (github or SRA base on your star protocol paper) and process with your commands, I encounter below issues. Do you know how to deal with the problem? My mixcr version also is 3.0.13.

**mixcr analyze shotgun -s hsa --starting-material rna --align "-OsaveOriginalReads=true" --assemble "--write-alignments" downsampled_reads/pt16_downsample_L001_R2_001.fastq.gz mixcr_output_test/clones**

NOTE: report file is not specified, using mixcr_output_test/clones.report to write report.
picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAnalyze$CommandShotgun@11fc564b): java.lang.RuntimeException: java.io.FileNotFoundException: mixcr_output_test/clones.vdjca (No such file or directory)
	at picocli.CommandLine.execute(CommandLine.java:1004)
	at picocli.CommandLine.access$900(CommandLine.java:142)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:76)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:65)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
	at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:89)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:59)
	at com.milaboratory.mixcr.cli.Main1.main(Main1.java:61)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: mixcr_output_test/clones.vdjca (No such file or directory)
	at com.milaboratory.cli.ACommand.run(ACommand.java:94)
	at com.milaboratory.mixcr.cli.CommandAnalyze.run0(CommandAnalyze.java:668)
	at com.milaboratory.cli.ACommand.run(ACommand.java:90)
	at picocli.CommandLine.execute(CommandLine.java:996)
	... 8 more
Caused by: java.io.FileNotFoundException: mixcr_output_test/clones.vdjca (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at com.milaboratory.mixcr.basictypes.IOUtil.createOS(IOUtil.java:160)
	at com.milaboratory.mixcr.basictypes.VDJCAlignmentsWriter.<init>(VDJCAlignmentsWriter.java:106)
	at com.milaboratory.mixcr.basictypes.VDJCAlignmentsWriter.<init>(VDJCAlignmentsWriter.java:98)
	at com.milaboratory.mixcr.cli.CommandAlign.run1(CommandAlign.java:487)
	at com.milaboratory.cli.ACommandWithSmartOverwrite.run0(ACommandWithSmartOverwrite.java:118)
	at com.milaboratory.cli.ACommand.run(ACommand.java:90)
	... 11 more

**Comment by whhudson** [comment]
Hello,

It seems mixcr cannot find the folder "mixcr_output_test", which is where you are attempting to write output.  Make sure that you are using the name of a folder that exists. Note that your folder name is different than the one supplied in the repository, which is "mixcr_output".

**Comment by kangxiongbin** [comment]
> Hello,
> 
> It seems mixcr cannot find the folder "mixcr_output_test", which is where you are attempting to write output. Make sure that you are using the name of a folder that exists. Note that your folder name is different than the one supplied in the repository, which is "mixcr_output".

Thanks for your answer! I forget to generate the folder mixcr_output_test, now it work.
